#!/usr/bin/env Rscript

# math-tools MCP Server
# Generated by mcpr (https://github.com/chi2labs/mcpr)
# 
# This server uses the enhanced MCPProtocolHandler for robust communication

# Suppress all package startup messages
suppressPackageStartupMessages({
  library(mcpr)
  library(jsonlite)
})

# Server configuration
SERVER_NAME <- "math-tools"
SERVER_VERSION <- "1.0.0"

# Check if we are in protocol mode
USE_PROTOCOL <- Sys.getenv("MCPR_USE_PROTOCOL", "true") != "false"

# Create server instance
server <- mcp(name = SERVER_NAME, version = SERVER_VERSION)

# Register tools
server$mcp_tool("add", function (a, b)  {     a + b }, "Add two numbers together")
server$mcp_tool("subtract", function (a, b)  {     a - b }, "Subtract one number from another")
server$mcp_tool("multiply", function (a, b)  {     a * b }, "Multiply two numbers")
server$mcp_tool("divide", function (a, b)  {     if (b == 0) {         stop("Division by zero is not allowed")     }     a/b }, "Divide one number by another")
server$mcp_tool("sqrt_custom", function (x)  {     if (x < 0) {         stop("Cannot calculate square root of negative number")     }     sqrt(x) }, "Calculate the square root of a number")

# Register resources
server$mcp_resource("get_constants", function() { "get_constants content" }, "Get math constants")

# Register prompts
server$mcp_prompt("math_solver_prompt", "Please solve the following math problem: {{problem}}. Show your work step by step.", "Prompt for solving a math problem")

# Load source files
source("/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/mcpr/examples/math-tools.R")

# Create and start transport
if (USE_PROTOCOL) {
  # Use enhanced protocol transport
  transport <- ProtocolStdioTransport$new(server)
} else {
  # Use legacy transport
  transport <- StdioTransport$new(server)
}

# Start the server
transport$start()

# Server will run until EOF is received
