#!/usr/bin/env Rscript

# {{SERVER_NAME}} MCP Server
# Generated by mcpr (https://github.com/chi2labs/mcpr)
# 
# IMPORTANT: This server must not output ANYTHING to stderr
# Any stderr output will break the MCP client connection

# Suppress all package startup messages
suppressPackageStartupMessages({
  library(jsonlite)
  {{ADDITIONAL_LIBRARIES}}
})

# Server configuration
SERVER_INFO <- list(
  name = "{{SERVER_NAME}}",
  version = "{{SERVER_VERSION}}"
)

# Create a blocking stdin connection
stdin_con <- file("stdin", open = "r", blocking = TRUE)
on.exit(close(stdin_con))

# Helper function to read JSON-RPC from stdin
read_json_rpc <- function() {
  line <- tryCatch({
    readLines(stdin_con, n = 1, warn = FALSE)
  }, error = function(e) {
    NULL
  })
  
  if (length(line) > 0 && nchar(line[1]) > 0) {
    return(line[1])
  }
  return(NULL)
}

# Send JSON-RPC response
send_response <- function(response) {
  cat(toJSON(response, auto_unbox = TRUE), "\n", sep = "")
  flush(stdout())
}

# Send error response
send_error <- function(id, code, message, data = NULL) {
  response <- list(
    jsonrpc = "2.0",
    id = id,
    error = list(
      code = code,
      message = message
    )
  )
  if (!is.null(data)) {
    response$error$data <- data
  }
  send_response(response)
}

# Tool definitions
TOOLS <- list(
{{TOOLS_DEFINITION}}
)

# Resource definitions
RESOURCES <- list(
{{RESOURCES_DEFINITION}}
)

# Prompt definitions
PROMPTS <- list(
{{PROMPTS_DEFINITION}}
)

# Tool implementations
{{TOOL_IMPLEMENTATIONS}}

# Resource implementations
{{RESOURCE_IMPLEMENTATIONS}}

# Main server loop
repeat {
  request_line <- read_json_rpc()
  
  if (is.null(request_line)) {
    # EOF reached, exit gracefully
    break
  }
  
  # Parse the JSON-RPC request
  request <- tryCatch({
    fromJSON(request_line, simplifyVector = FALSE)
  }, error = function(e) {
    send_error(NULL, -32700, "Parse error", as.character(e))
    NULL
  })
  
  if (is.null(request)) {
    next
  }
  
  # Extract request components
  method <- request$method
  params <- if (!is.null(request$params)) request$params else list()
  id <- request$id
  
  # Route the request to appropriate handler
  result <- NULL
  error <- NULL
  
  tryCatch({
    if (method == "initialize") {
      # Handle initialization
      result <- list(
        protocolVersion = "2024-11-05",
        capabilities = list(
          tools = if (length(TOOLS) > 0) TOOLS else list(),
          resources = if (length(RESOURCES) > 0) RESOURCES else list(),
          prompts = if (length(PROMPTS) > 0) PROMPTS else list()
        ),
        serverInfo = SERVER_INFO
      )
      
    } else if (method == "initialized") {
      # Client notification - no response needed
      next
      
    } else if (method == "tools/list") {
      # List available tools
      result <- list(
        tools = if (length(TOOLS) > 0) unname(TOOLS) else list()
      )
      
    } else if (method == "tools/call") {
      # Execute a tool
      tool_name <- params$name
      tool_args <- if (!is.null(params$arguments)) params$arguments else list()
      
      # Find and execute the tool
      if (!is.null(tool_name) && exists(paste0("tool_", tool_name))) {
        tool_fn <- get(paste0("tool_", tool_name))
        tool_result <- do.call(tool_fn, tool_args)
        
        # Format the result
        result <- list(
          content = list(list(
            type = "text",
            text = if (is.character(tool_result) && length(tool_result) == 1) {
              tool_result
            } else {
              toJSON(tool_result, auto_unbox = TRUE, pretty = TRUE)
            }
          ))
        )
      } else {
        error <- list(
          code = -32002,
          message = "Tool not found",
          data = paste("Unknown tool:", tool_name)
        )
      }
      
    } else if (method == "resources/list") {
      # List available resources
      result <- list(
        resources = if (length(RESOURCES) > 0) unname(RESOURCES) else list()
      )
      
    } else if (method == "resources/read") {
      # Read a resource
      resource_uri <- params$uri
      
      if (!is.null(resource_uri) && exists(paste0("resource_", resource_uri))) {
        resource_fn <- get(paste0("resource_", resource_uri))
        resource_content <- resource_fn()
        
        # Find resource metadata
        resource_meta <- NULL
        for (r in RESOURCES) {
          if (r$uri == resource_uri) {
            resource_meta <- r
            break
          }
        }
        
        result <- list(
          contents = list(list(
            uri = resource_uri,
            mimeType = if (!is.null(resource_meta)) resource_meta$mimeType else "text/plain",
            text = if (is.character(resource_content) && length(resource_content) == 1) {
              resource_content
            } else {
              toJSON(resource_content, auto_unbox = TRUE, pretty = TRUE)
            }
          ))
        )
      } else {
        error <- list(
          code = -32002,
          message = "Resource not found",
          data = paste("Unknown resource:", resource_uri)
        )
      }
      
    } else if (method == "prompts/list") {
      # List available prompts
      result <- list(
        prompts = if (length(PROMPTS) > 0) unname(PROMPTS) else list()
      )
      
    } else if (method == "prompts/get") {
      # Get a prompt
      prompt_name <- params$name
      prompt_args <- if (!is.null(params$arguments)) params$arguments else list()
      
      # Find the prompt
      prompt <- NULL
      for (p in PROMPTS) {
        if (p$name == prompt_name) {
          prompt <- p
          break
        }
      }
      
      if (!is.null(prompt)) {
        # Simple template substitution
        text <- prompt$template
        for (arg_name in names(prompt_args)) {
          pattern <- paste0("{{", arg_name, "}}")
          text <- gsub(pattern, prompt_args[[arg_name]], text, fixed = TRUE)
        }
        
        result <- list(
          messages = list(
            list(
              role = "user",
              content = list(
                type = "text",
                text = text
              )
            )
          )
        )
      } else {
        error <- list(
          code = -32002,
          message = "Prompt not found",
          data = paste("Unknown prompt:", prompt_name)
        )
      }
      
    } else {
      # Unknown method
      error <- list(
        code = -32601,
        message = "Method not found",
        data = paste("Unknown method:", method)
      )
    }
    
  }, error = function(e) {
    error <<- list(
      code = -32603,
      message = "Internal error",
      data = as.character(e)
    )
  })
  
  # Send response if this was a request (has an id)
  if (!is.null(id)) {
    response <- list(
      jsonrpc = "2.0",
      id = id
    )
    
    if (!is.null(error)) {
      response$error <- error
    } else if (!is.null(result)) {
      response$result <- result
    } else {
      response$result <- list()
    }
    
    send_response(response)
  }
}

# Clean shutdown - no output to stderr!